/** Only this product-owned submission can publish generated bytes to candidate validation. */
export const widgetSubmitToolName = "submit_widget_candidate";
export const widgetToolWireLimit = 6 * 1_048_576 + 4096;
export const widgetSubmitParameters = {
  type: "object",
  properties: {
    package: {
      type: "string",
      description:
        "Complete UTF-8 JSON widget package, schemaVersion 1, at most 1 MiB before JSON string escaping.",
    },
  },
  required: ["package"],
  additionalProperties: false,
};
export function validWidgetSubmission(
  value: unknown,
): value is { package: string } {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const v = value as Record<string, unknown>;
  return (
    Object.keys(v).join(",") === "package" &&
    typeof v.package === "string" &&
    new TextEncoder().encode(v.package).length <= 1_048_576
  );
}
